<a href="https://colab.research.google.com/github/Kushalsharma12345/kushal/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
arr= np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
import numpy as np
arr= np.array(42)
print(arr)

42


In [ ]:
import numpy as np
arr= np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [ ]:
import numpy as np
arr= np.array([[1, 2, 3], [4, 5, 6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
import numpy as np
a= np.array(42)
b= np.array([1, 2, 3, 4, 5])
c= np.array([[1, 2, 3], [4, 5, 6]])
d= np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [ ]:
import numpy as np
arr= np.array([1, 2, 3, 4], ndmin=5)
print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5])
print(arr[4:])
print(arr[:4])
print(arr[-3:-1])
print(arr[1:5:2])
print(arr[::2])

[2 3 4 5]
[5 6 7]
[1 2 3 4]
[5 6]
[2 4]
[1 3 5 7]


In [ ]:
import numpy as np
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[1, 1:4])

[7 8 9]


In [ ]:
import numpy as np
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[0:2, 2])
print(arr[0:2, 1:4])

[3 8]
[[2 3 4]
 [7 8 9]]


In [ ]:
import numpy as np
arr = np.array([1.1, 2.1, 3.1])
newarr = arr.astype('i')
print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [ ]:
import numpy as np
a= np.array([[1,2,3],[4,5,6]])
print(a.shape )
a= np.array([[1,2,3],[4,5,6]])
a.shape = (3,2)
print(a )
a= np.array([[1,2,3],[4,5,6]])
b= a.reshape(3,2)
print(b)

(2, 3)
[[1 2]
 [3 4]
 [5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [ ]:
import numpy as np
a= np.arange(24)
print (a)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [ ]:
import numpy as np
a= np.arange(24)
a.ndim
b = a.reshape(2,4,3)
print (b)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]


In [ ]:
import numpy as np
x= np.array([1,2,3,4,5], dtype = np.int8)
print(x.itemsize )

1


In [ ]:
import numpy as np
x = np.array([1,2,3,4,5], dtype = np.float32)
print(x.itemsize)

4


In [ ]:
import numpy as np
x= np.array([1,2,3,4,5])
print(x.flags)

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False



In [ ]:
import numpy as np
x= np.array([[1, 2], [3, 4], [5, 6]])
y= x[[0,1,2], [0,1,0]]
print(y)
x= np.array([[ 0, 1, 2],[ 3, 4, 5],[ 6, 7, 8],[ 9, 10, 11]])
print('Our array is:',x)
rows= np.array([[0,0],[3,3]])
cols= np.array([[0,2],[0,2]])
y= x[rows,cols]
print ('The corner elements of this array are:' ,y)

[1 4 5]
Our array is: [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
The corner elements of this array are: [[ 0  2]
 [ 9 11]]


In [ ]:
import numpy as np
arr= np.array([1, 2, 3, 4, 5, 4, 4])
x= np.where(arr == 4)
print(x)

(array([3, 5, 6]),)


In [ ]:
import numpy as np
arr= np.array([1, 2, 3, 4, 5, 6, 7, 8])
x= np.where(arr%2 == 0)
print(x)

(array([1, 3, 5, 7]),)


In [ ]:
import numpy as np
arr= np.array([6, 7, 8, 9])
x= np.searchsorted(arr, 7)
print(x)

1


In [ ]:
import numpy as np
arr= np.array([6, 7, 8, 9])
x= np.searchsorted(arr, 7, side='right')
print(x)

2


In [ ]:
import numpy as np
arr= np.array([1, 3, 5, 7])
x= np.searchsorted(arr, [2, 4, 6])
print(x)

[1 2 3]


In [ ]:
import numpy as np
arr1= np.array([1, 2, 3])
arr2= np.array([4, 5, 6])
arr= np.concatenate((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


In [ ]:
import numpy as np
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
arr = np.concatenate((arr1, arr2), axis=1)
print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [ ]:
import numpy as np
arr1= np.array([1, 2, 3])
arr2= np.array([4, 5, 6])
arr= np.stack((arr1, arr2), axis=1)
print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [ ]:
import numpy as np
arr1= np.array([1, 2, 3])
arr2= np.array([4, 5, 6])
arr= np.hstack((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


In [ ]:
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.vstack((arr1, arr2))
print(arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.dstack((arr1, arr2))
print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 3)
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 4)
print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42
print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [ ]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42
print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
x[0] = 31
print(arr)
print(x)

[31  2  3  4  5]
[31  2  3  4  5]
